# Generated by Django 5.1 on 2026-04-24 20:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_label', models.CharField(default='Room', max_length=50)),
                ('room_type', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared')], max_length=20)),
                ('bed_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('queen', 'Queen'), ('king', 'King'), ('mattress', 'Mattress')], max_length=30)),
                ('bed_count', models.SmallIntegerField(default=1)),
                ('max_guests', models.SmallIntegerField(default=1)),
                ('bathroom_type', models.CharField(choices=[('attached', 'Attached'), ('shared', 'Shared')], max_length=20)),
                ('room_features', models.JSONField(default=dict)),
                ('room_size_sqft', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.property')),
            ],
            options={
                'db_table': 'rooms',
                'indexes': [models.Index(fields=['property'], name='idx_rooms_property')],
                'constraints': [models.UniqueConstraint(fields=('property', 'room_label'), name='uq_rooms_property_label')],
            },
        ),
    ]
