# Generated by Django 5.1 on 2026-07-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_size_sqft',
        ),
    ]
