# Generated by Django 5.1 on 2026-04-24 20:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=20, null=True)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'booking status histories',
                'db_table': 'booking_status_history',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_code', models.CharField(max_length=20, unique=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('number_of_guests', models.SmallIntegerField(default=1)),
                ('guest_purpose', models.CharField(blank=True, max_length=50, null=True)),
                ('booking_mode', models.CharField(choices=[('instant', 'Instant'), ('request', 'Request')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled_by_guest', 'Cancelled By Guest'), ('cancelled_by_host', 'Cancelled By Host'), ('active', 'Active'), ('completed', 'Completed'), ('no_show', 'No Show'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('host_nightly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guest_nightly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_guest_pays', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_host_receives', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('host_responded_at', models.DateTimeField(blank=True, null=True)),
                ('host_response_deadline', models.DateTimeField(blank=True, null=True)),
                ('guest_checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('guest_checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('cancellation_policy', models.CharField(blank=True, choices=[('flexible', 'Flexible'), ('moderate', 'Moderate'), ('strict', 'Strict')], max_length=20, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings_as_guest', to='users.user')),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings_as_host', to='users.user')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
