# Generated by Django 5.1 on 2026-04-24 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('listings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='bookingstatushistory',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingstatushistory',
            name='changed_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_status_changes', to='users.user'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['guest_user'], name='idx_bookings_guest'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['host_user'], name='idx_bookings_host'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['listing'], name='idx_bookings_listing'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='idx_bookings_status'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('check_out_date__gt', models.F('check_in_date'))), name='valid_dates'),
        ),
    ]
