# Generated by Django 5.1 on 2026-05-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('payment_pending', 'Payment Pending'), ('paid', 'Paid'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('failed', 'Failed')], default='unpaid', max_length=25),
        ),
    ]
