# Generated by Django 5.2.13 on 2026-05-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_add_meal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='host_platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
