# Generated by Django 5.1 on 2026-04-24 20:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('host_price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_pct', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('platform_fee_pct', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('weekly_discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('monthly_discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('min_nights', models.SmallIntegerField(default=1)),
                ('max_nights', models.SmallIntegerField(default=30)),
                ('advance_notice_hours', models.SmallIntegerField(blank=True, default=24, null=True)),
                ('booking_mode', models.CharField(choices=[('instant', 'Instant'), ('request', 'Request')], default='request', max_length=20)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('food_kitchen_access', models.BooleanField(default=False)),
                ('food_meals_available', models.BooleanField(default=False)),
                ('food_meal_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('food_meal_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('paused', 'Paused'), ('snoozed', 'Snoozed'), ('delisted', 'Delisted')], default='draft', max_length=20)),
                ('snoozed_until', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('total_bookings', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='users.user')),
            ],
            options={
                'db_table': 'listings',
            },
        ),
        migrations.CreateModel(
            name='ListingAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'listing_amenities',
            },
        ),
        migrations.CreateModel(
            name='ListingHouseRules',
            fields=[
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='house_rules', serialize=False, to='listings.listing')),
                ('no_smoking', models.BooleanField(default=True)),
                ('no_loud_music_after', models.TimeField(default='22:00')),
                ('no_alcohol', models.BooleanField(default=False)),
                ('no_pets', models.BooleanField(default=True)),
                ('no_visitors', models.BooleanField(default=False)),
                ('no_overnight_guests', models.BooleanField(default=True)),
                ('min_guest_age', models.SmallIntegerField(default=18)),
                ('custom_rules', models.TextField(blank=True, null=True)),
                ('check_in_from', models.TimeField(default='14:00')),
                ('check_in_until', models.TimeField(default='22:00')),
                ('check_out_by', models.TimeField(default='11:00')),
                ('cancellation_policy', models.CharField(choices=[('flexible', 'Flexible'), ('moderate', 'Moderate'), ('strict', 'Strict')], default='moderate', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'listing house rules',
                'db_table': 'listing_house_rules',
            },
        ),
    ]
