# Generated by Django 5.1 on 2026-04-24 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amenities', '0001_initial'),
        ('listings', '0001_initial'),
        ('properties', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='properties.property'),
        ),
        migrations.AddField(
            model_name='listing',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='listingamenity',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_amenities', to='amenities.amenitydefinition'),
        ),
        migrations.AddField(
            model_name='listingamenity',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_amenities', to='listings.listing'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['host_user'], name='idx_listings_host'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status'], name='idx_listings_status'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['property'], name='idx_listings_property'),
        ),
        migrations.AddConstraint(
            model_name='listingamenity',
            constraint=models.UniqueConstraint(fields=('listing', 'amenity'), name='pk_listing_amenities'),
        ),
    ]
