# Generated by Django 5.2.13 on 2026-05-12 16:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingBlockedDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='listings.listing')),
            ],
            options={
                'db_table': 'listing_blocked_dates',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['listing', 'start_date', 'end_date'], name='idx_blocked_dates_range')],
            },
        ),
    ]
