# Generated by Django 5.2.13 on 2026-05-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_add_listing_blocked_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='platform_fee_pct',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
