# Generated by Django 5.2.13 on 2026-05-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_platform_fee_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('live', 'Live'), ('paused', 'Paused'), ('snoozed', 'Snoozed'), ('delisted', 'Delisted')], default='draft', max_length=20),
        ),
    ]
