# Generated by Django 5.1 on 2026-07-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_add_pending_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='cook_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='cook_cost_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='maid_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='maid_cost_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='maintenance_monthly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='min_months',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='rental_type',
            field=models.CharField(choices=[('nightly', 'Nightly'), ('monthly', 'Monthly')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='setup_cost_onetime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='setup_cost_refundable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='utilities_est_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='utilities_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='host_price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
