# Generated by Django 5.1 on 2026-10-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_backfill_rental_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='available_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_term',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary')], default='permanent', max_length=10),
        ),
    ]
