# Generated by Django 5.1 on 2026-10-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_term_available_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='term_ended_notified_for',
            field=models.DateField(blank=True, null=True),
        ),
    ]
