# Generated by Django 5.1 on 2026-05-08 18:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_payoutaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('booking.payment_succeeded', 'Booking payment succeeded'), ('booking.payment_failed', 'Booking payment failed'), ('booking.host_accepted', 'Host accepted booking'), ('booking.host_rejected', 'Host rejected booking'), ('booking.guest_cancelled', 'Guest cancelled booking'), ('booking.host_cancelled', 'Host cancelled booking'), ('booking.refund_initiated', 'Refund initiated'), ('booking.refund_completed', 'Refund completed')], max_length=64)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], max_length=16)),
                ('subject_template', models.CharField(blank=True, help_text='Used for email only; SMS ignores this.', max_length=255)),
                ('body_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'channel'], name='idx_notif_template_lookup')],
                'constraints': [models.UniqueConstraint(fields=('event_type', 'channel'), name='uq_notif_template_event_channel')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('booking.payment_succeeded', 'Booking payment succeeded'), ('booking.payment_failed', 'Booking payment failed'), ('booking.host_accepted', 'Host accepted booking'), ('booking.host_rejected', 'Host rejected booking'), ('booking.guest_cancelled', 'Guest cancelled booking'), ('booking.host_cancelled', 'Host cancelled booking'), ('booking.refund_initiated', 'Refund initiated'), ('booking.refund_completed', 'Refund completed')], max_length=64)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('dead', 'Dead'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('recipient_address', models.CharField(help_text='Email, phone (with country code), or push token.', max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('last_error', models.TextField(blank=True)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=5)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.user')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='idx_notif_status_next'), models.Index(fields=['user', '-created_at'], name='idx_notif_user_created'), models.Index(fields=['user', 'read_at'], name='idx_notif_user_read')],
                'constraints': [models.UniqueConstraint(fields=('idempotency_key', 'channel'), name='uq_notif_idem_channel')],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('booking.payment_succeeded', 'Booking payment succeeded'), ('booking.payment_failed', 'Booking payment failed'), ('booking.host_accepted', 'Host accepted booking'), ('booking.host_rejected', 'Host rejected booking'), ('booking.guest_cancelled', 'Guest cancelled booking'), ('booking.host_cancelled', 'Host cancelled booking'), ('booking.refund_initiated', 'Refund initiated'), ('booking.refund_completed', 'Refund completed')], max_length=64)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='users.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'event_type', 'channel'], name='idx_notif_pref_lookup')],
                'constraints': [models.UniqueConstraint(fields=('user', 'event_type', 'channel'), name='uq_notif_pref_user_event_channel')],
            },
        ),
    ]
