# Generated by Django 5.1 on 2026-05-08 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
        migrations.AlterModelTable(
            name='notificationtemplate',
            table='notification_templates',
        ),
        migrations.AlterModelTable(
            name='usernotificationpreference',
            table='user_notification_preferences',
        ),
    ]
