# Generated by Django 5.1 on 2026-06-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('in_app', 'In-app')], max_length=16),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('booking.payment_succeeded', 'Booking payment succeeded'), ('booking.payment_failed', 'Booking payment failed'), ('booking.host_accepted', 'Host accepted booking'), ('booking.host_rejected', 'Host rejected booking'), ('booking.guest_cancelled', 'Guest cancelled booking'), ('booking.host_cancelled', 'Host cancelled booking'), ('booking.refund_initiated', 'Refund initiated'), ('booking.refund_completed', 'Refund completed'), ('message.received', 'New message received'), ('id_verification.approved', 'ID verification approved'), ('id_verification.rejected', 'ID verification rejected')], max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('in_app', 'In-app')], max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('booking.payment_succeeded', 'Booking payment succeeded'), ('booking.payment_failed', 'Booking payment failed'), ('booking.host_accepted', 'Host accepted booking'), ('booking.host_rejected', 'Host rejected booking'), ('booking.guest_cancelled', 'Guest cancelled booking'), ('booking.host_cancelled', 'Host cancelled booking'), ('booking.refund_initiated', 'Refund initiated'), ('booking.refund_completed', 'Refund completed'), ('message.received', 'New message received'), ('id_verification.approved', 'ID verification approved'), ('id_verification.rejected', 'ID verification rejected')], max_length=64),
        ),
        migrations.AlterField(
            model_name='usernotificationpreference',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('in_app', 'In-app')], max_length=16),
        ),
        migrations.AlterField(
            model_name='usernotificationpreference',
            name='event_type',
            field=models.CharField(choices=[('booking.payment_succeeded', 'Booking payment succeeded'), ('booking.payment_failed', 'Booking payment failed'), ('booking.host_accepted', 'Host accepted booking'), ('booking.host_rejected', 'Host rejected booking'), ('booking.guest_cancelled', 'Guest cancelled booking'), ('booking.host_cancelled', 'Host cancelled booking'), ('booking.refund_initiated', 'Refund initiated'), ('booking.refund_completed', 'Refund completed'), ('message.received', 'New message received'), ('id_verification.approved', 'ID verification approved'), ('id_verification.rejected', 'ID verification rejected')], max_length=64),
        ),
    ]
