# Generated by Django 5.1 on 2026-07-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('booking.new', 'New booking received'), ('booking.payment_succeeded', 'Booking payment succeeded'), ('booking.payment_failed', 'Booking payment failed'), ('booking.host_accepted', 'Host accepted booking'), ('booking.host_rejected', 'Host rejected booking'), ('booking.guest_cancelled', 'Guest cancelled booking'), ('booking.host_cancelled', 'Host cancelled booking'), ('booking.refund_initiated', 'Refund initiated'), ('booking.refund_completed', 'Refund completed'), ('contact.unlocked', 'Guest unlocked host contact'), ('message.received', 'New message received'), ('id_verification.approved', 'ID verification approved'), ('id_verification.rejected', 'ID verification rejected')], max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('booking.new', 'New booking received'), ('booking.payment_succeeded', 'Booking payment succeeded'), ('booking.payment_failed', 'Booking payment failed'), ('booking.host_accepted', 'Host accepted booking'), ('booking.host_rejected', 'Host rejected booking'), ('booking.guest_cancelled', 'Guest cancelled booking'), ('booking.host_cancelled', 'Host cancelled booking'), ('booking.refund_initiated', 'Refund initiated'), ('booking.refund_completed', 'Refund completed'), ('contact.unlocked', 'Guest unlocked host contact'), ('message.received', 'New message received'), ('id_verification.approved', 'ID verification approved'), ('id_verification.rejected', 'ID verification rejected')], max_length=64),
        ),
        migrations.AlterField(
            model_name='usernotificationpreference',
            name='event_type',
            field=models.CharField(choices=[('booking.new', 'New booking received'), ('booking.payment_succeeded', 'Booking payment succeeded'), ('booking.payment_failed', 'Booking payment failed'), ('booking.host_accepted', 'Host accepted booking'), ('booking.host_rejected', 'Host rejected booking'), ('booking.guest_cancelled', 'Guest cancelled booking'), ('booking.host_cancelled', 'Host cancelled booking'), ('booking.refund_initiated', 'Refund initiated'), ('booking.refund_completed', 'Refund completed'), ('contact.unlocked', 'Guest unlocked host contact'), ('message.received', 'New message received'), ('id_verification.approved', 'ID verification approved'), ('id_verification.rejected', 'ID verification rejected')], max_length=64),
        ),
    ]
