# Generated by Django 5.1 on 2026-07-13 16:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_event_type_and_more'),
        ('users', '0007_rename_non_binary_to_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='Expo push token, e.g. ExponentPushToken[xxxx].', max_length=255, unique=True)),
                ('platform', models.CharField(blank=True, max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='users.user')),
            ],
            options={
                'db_table': 'device_tokens',
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_devtok_user_active')],
            },
        ),
    ]
