# Generated by Django 5.1 on 2026-04-25 12:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(help_text='Full phone with country code, e.g. +919935361905', max_length=20)),
                ('otp_hash', models.CharField(help_text='SHA-256 hash of the OTP code', max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('attempt_count', models.SmallIntegerField(default=0)),
                ('max_attempts', models.SmallIntegerField(default=3)),
                ('is_consumed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='users.user')),
            ],
            options={
                'db_table': 'otp_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', '-created_at'], name='idx_otp_phone_created')],
            },
        ),
    ]
