# Generated by Django 5.1 on 2026-04-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
