# Generated by Django 5.1 on 2026-04-30 07:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('bank', 'Bank'), ('upi', 'Upi')], max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('account_holder_name', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=11, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_accounts', to='users.user')),
            ],
            options={
                'db_table': 'payout_accounts',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
