# Generated by Django 5.2.13 on 2026-05-24 17:53

from django.db import migrations, models


def rename_non_binary(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    UserProfile.objects.filter(gender='non_binary').update(gender='other')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_aadhaar_photo_url_and_more'),
    ]

    operations = [
        migrations.RunPython(rename_non_binary, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer Not To Say')], max_length=20),
        ),
    ]
