# Generated by Django 5.1 on 2026-06-04 18:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0006_add_host_platform_fee'),
        ('users', '0007_rename_non_binary_to_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guest_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('host_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='bookings.booking')),
                ('guest_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='conversations_as_guest', to='users.user')),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='conversations_as_host', to='users.user')),
            ],
            options={
                'db_table': 'conversations',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sent_messages', to='users.user')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['guest_user', '-last_message_at'], name='idx_conv_guest_lastmsg'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['host_user', '-last_message_at'], name='idx_conv_host_lastmsg'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='idx_msg_conv_created'),
        ),
    ]
