# Generated by Django 5.1 on 2026-07-15 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_guest_email_booking_guest_gender_and_more'),
        ('conversations', '0001_initial'),
        ('listings', '0005_add_pending_status'),
        ('users', '0007_rename_non_binary_to_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='bookings.booking'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('booking__isnull', True)), fields=('guest_user', 'host_user', 'listing'), name='uq_conv_inquiry_guest_host_listing'),
        ),
    ]
