# Generated by Django 5.1 on 2026-04-24 20:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('apartment_type', models.CharField(choices=[('1bhk', 'Bhk 1'), ('2bhk', 'Bhk 2'), ('3bhk', 'Bhk 3'), ('4bhk', 'Bhk 4')], max_length=20)),
                ('floor_number', models.SmallIntegerField()),
                ('total_floors', models.SmallIntegerField(blank=True, null=True)),
                ('apartment_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('google_place_id', models.CharField(blank=True, max_length=300, null=True)),
                ('formatted_address', models.TextField(blank=True, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city_id', models.UUIDField()),
                ('neighborhood_id', models.UUIDField(blank=True, null=True)),
                ('city_name', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('gender_preference', models.CharField(choices=[('male_only', 'Male Only'), ('female_only', 'Female Only'), ('any', 'Any')], default='any', max_length=20)),
                ('ownership_type', models.CharField(choices=[('owner_occupied', 'Owner Occupied'), ('tenant', 'Tenant'), ('landlord_consent', 'Landlord Consent')], default='tenant', max_length=20)),
                ('landlord_consent_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('live', 'Live'), ('paused', 'Paused'), ('rejected', 'Rejected'), ('delisted', 'Delisted')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='properties', to='users.user')),
            ],
            options={
                'verbose_name_plural': 'properties',
                'db_table': 'properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyFlatmate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flatmates', to='properties.property')),
            ],
            options={
                'db_table': 'property_flatmates',
            },
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area', models.CharField(choices=[('bedroom', 'Bedroom'), ('washroom', 'Washroom'), ('kitchen', 'Kitchen'), ('living_room', 'Living Room'), ('other', 'Other')], max_length=30)),
                ('url', models.URLField(max_length=2048)),
                ('thumbnail_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.property')),
            ],
            options={
                'db_table': 'property_photos',
            },
        ),
    ]
