# Generated by Django 5.1 on 2026-04-24 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyphoto',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rooms.room'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['host_user'], name='idx_properties_host'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city_id'], name='idx_properties_city'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='idx_properties_status'),
        ),
        migrations.AddIndex(
            model_name='propertyflatmate',
            index=models.Index(fields=['property'], name='idx_flatmates_property'),
        ),
        migrations.AddIndex(
            model_name='propertyphoto',
            index=models.Index(fields=['property'], name='idx_photos_property'),
        ),
        migrations.AddConstraint(
            model_name='propertyphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('property',), name='uniq_cover_photo'),
        ),
    ]
