# Generated by Django 5.1 on 2026-05-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_nullable_geo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='property',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
