# Generated by Django 5.2.13 on 2026-05-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_nullable_lat_lng_city_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyphoto',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='propertyphoto',
            name='url',
            field=models.CharField(max_length=2048),
        ),
    ]
