# Generated by Django 5.2.13 on 2026-05-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_change_photo_url_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
