# Generated by Django 5.2.13 on 2026-05-11 13:37

import django.core.validators
from django.db import migrations, models


def nullify_empty_pincodes(apps, schema_editor):
    Property = apps.get_model('properties', 'Property')
    Property.objects.filter(pincode='').update(pincode=None)


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_add_field_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        # First make pincode nullable as a CharField so empty strings can become NULL
        migrations.AlterField(
            model_name='property',
            name='pincode',
            field=models.CharField(max_length=10, null=True, blank=True),
        ),
        # Convert empty strings to NULL
        migrations.RunPython(nullify_empty_pincodes, migrations.RunPython.noop),
        # Now safely convert to IntegerField
        migrations.AlterField(
            model_name='property',
            name='pincode',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
