# Generated by Django 5.2.13 on 2026-05-24 17:01

from django.db import migrations, models


def empty_pincode_to_null(apps, schema_editor):
    Property = apps.get_model("properties", "Property")
    Property.objects.filter(pincode="").update(pincode=None)


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_add_state_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='pincode',
            field=models.CharField(max_length=10, null=True, blank=True),
        ),
        migrations.RunPython(empty_pincode_to_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='property',
            name='pincode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
