# Generated by Django 5.2.13 on 2026-05-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_add_state_convert_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyflatmate',
            name='native_town',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
