# Generated by Django 5.1 on 2026-07-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_pincode_to_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyflatmate',
            name='hometown',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
