export const ENDPOINTS = {
  AUTH: {
    SEND_OTP: '/api/users/auth/otp/send/',
    VERIFY_OTP: '/api/users/auth/otp/verify/',
    COMPLETE_PROFILE: '/api/users/auth/profile/complete/',
    REFRESH_TOKEN: '/api/users/auth/token/refresh/',
  },
  USER: {
    PROFILE: '/api/users/profile/me/',
    UPDATE_PROFILE: '/api/users/profile/update/',
    UPLOAD_PHOTO: '/api/users/profile/upload-photo/',
    SEND_EMAIL_VERIFICATION: '/api/users/profile/email/send-verification/',
    VERIFY_EMAIL: '/api/users/profile/email/verify/',
    VERIFICATION_STATUS: '/api/users/profile/verification-status/',
    SUBMIT_ID_VERIFICATION: '/api/users/profile/id-verification/submit/',
    PAYOUT_ACCOUNTS: '/api/users/profile/payout-accounts/',
    ADD_BANK: '/api/users/profile/payout-accounts/add-bank/',
    ADD_UPI: '/api/users/profile/payout-accounts/add-upi/',
    DELETE_ACCOUNT: '/api/users/profile/delete-account/',
  },
  HOST: {
    DASHBOARD: '/api/users/host/dashboard/',
    BOOKINGS: '/api/bookings/host/',
    EARNINGS: '/api/bookings/host/earnings/',
    LISTINGS: '/api/listings/host/',
    CREATE_LISTING: '/api/listings/',
    LISTING_DETAIL: (id: string) => `/api/listings/${id}/`,
    LISTING_BLOCKED_DATES: (id: string) => `/api/listings/${id}/blocked-dates/`,
    LISTING_SNOOZE: (id: string) => `/api/listings/${id}/snooze/`,
    PROPERTIES: '/api/properties/',
    PROPERTY_PHOTOS: (propertyId: string) => `/api/properties/${propertyId}/photos/`,
  },
  GUEST: {
    SEARCH: '/api/listings/search/',
    LISTING_DETAIL: (id: string) => `/api/listings/guest/${id}/`,
    BOOKINGS: '/api/bookings/guest/',
  },
  BOOKING: {
    QUOTE: '/api/bookings/quote/',
    CREATE: '/api/bookings/create/',
    CANCEL: (bookingId: string) => `/api/bookings/${bookingId}/cancel/`,
  },
  PAYMENT: {
    CREATE_ORDER: '/api/payments/create-order/',
    VERIFY: '/api/payments/verify/',
    UNLOCK_CREATE_ORDER: '/api/payments/unlock/create-order/',
    UNLOCK_VERIFY: '/api/payments/unlock/verify/',
    HOST_PAYOUTS: '/api/payments/host/payouts/',
  },
  NOTIFICATIONS: {
    LIST: '/api/notifications/',
    MARK_READ: (id: string) => `/api/notifications/${id}/read/`,
    MARK_ALL_READ: '/api/notifications/read-all/',
    PREFERENCES: '/api/notifications/preferences/',
  },
  CHAT: {
    CONVERSATIONS: '/api/conversations/',
    MESSAGES: (conversationId: string) => `/api/conversations/${conversationId}/messages/`,
    READ: (conversationId: string) => `/api/conversations/${conversationId}/read/`,
  },
  AMENITIES: '/api/amenities/',
};