# Generated by Django 5.1 on 2026-04-24 20:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('display_order', models.SmallIntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'amenity categories',
                'db_table': 'amenity_categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='AmenityDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('display_order', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='amenities.amenitycategory')),
            ],
            options={
                'db_table': 'amenity_definitions',
                'ordering': ['display_order'],
            },
        ),
    ]
