# Generated by Django 5.1 on 2026-04-24 20:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('listings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_type', models.CharField(choices=[('guest_to_host', 'Guest To Host'), ('host_to_guest', 'Host To Guest')], max_length=20)),
                ('overall_rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cleanliness_rating', models.SmallIntegerField(blank=True, null=True)),
                ('accuracy_rating', models.SmallIntegerField(blank=True, null=True)),
                ('communication_rating', models.SmallIntegerField(blank=True, null=True)),
                ('location_rating', models.SmallIntegerField(blank=True, null=True)),
                ('value_rating', models.SmallIntegerField(blank=True, null=True)),
                ('food_rating', models.SmallIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('host_response', models.TextField(blank=True, null=True)),
                ('host_responded_at', models.DateTimeField(blank=True, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.booking')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='listings.listing')),
                ('reviewee_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='users.user')),
                ('reviewer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='users.user')),
            ],
            options={
                'db_table': 'reviews',
                'indexes': [models.Index(fields=['listing'], name='idx_reviews_listing')],
                'constraints': [models.UniqueConstraint(fields=('booking', 'review_type'), name='uq_reviews_booking_type'), models.CheckConstraint(condition=models.Q(('overall_rating__gte', 1), ('overall_rating__lte', 5)), name='valid_rating')],
            },
        ),
    ]
