# Generated by Django 5.1 on 2026-05-01 04:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_booking_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField()),
                ('signature_valid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'webhook_events',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_order_id', models.CharField(max_length=64, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('method', models.CharField(blank=True, choices=[('upi', 'Upi'), ('card', 'Card'), ('netbanking', 'Netbanking'), ('wallet', 'Wallet'), ('emi', 'Emi'), ('other', 'Other')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='created', max_length=25)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('error_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='bookings.booking')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_refund_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('guest_cancel', 'Guest Cancel'), ('host_cancel', 'Host Cancel'), ('auto_expire', 'Auto Expire'), ('dispute', 'Dispute'), ('ops_adjustment', 'Ops Adjustment')], max_length=30)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('processed', 'Processed'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='refunds', to='payments.payment')),
            ],
            options={
                'db_table': 'refunds',
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking'], name='idx_payments_booking'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='idx_payments_status'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['razorpay_order_id'], name='idx_payments_order'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment'], name='idx_refunds_payment'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status'], name='idx_refunds_status'),
        ),
    ]
