# Generated by Django 5.1 on 2026-05-14 13:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_add_meal_fields'),
        ('payments', '0001_initial'),
        ('users', '0005_payoutaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('method', models.CharField(choices=[('manual_bank', 'Manual Bank'), ('manual_upi', 'Manual Upi'), ('razorpay', 'Razorpay')], default='manual_bank', max_length=20)),
                ('transfer_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payout_id', models.CharField(blank=True, max_length=64, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('bookings', models.ManyToManyField(blank=True, related_name='payouts', to='bookings.booking')),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payouts', to='users.user')),
                ('payout_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.payoutaccount')),
            ],
            options={
                'db_table': 'payouts',
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['host_user', 'status'], name='idx_payouts_host_status')],
            },
        ),
    ]
