# Generated by Django 5.1

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_add_pending_status'),
        ('payments', '0002_payout'),
        ('users', '0007_rename_non_binary_to_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUnlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_order_id', models.CharField(max_length=64, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('unlocked', 'Unlocked'), ('failed', 'Failed')], default='created', max_length=20)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_unlocks', to='users.user')),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_unlocks_received', to='users.user')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_unlocks', to='listings.listing')),
            ],
            options={
                'db_table': 'contact_unlocks',
                'indexes': [models.Index(fields=['guest_user', 'listing'], name='idx_unlock_guest_listing'), models.Index(fields=['razorpay_order_id'], name='idx_unlock_order'), models.Index(fields=['status'], name='idx_unlock_status')],
            },
        ),
    ]
