# Generated by Django 5.1 on 2026-04-20 13:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('phone_country_code', models.CharField(default='+91', max_length=5)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('password_hash', models.TextField(blank=True, null=True)),
                ('auth_provider', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('google', 'Google'), ('apple', 'Apple'), ('facebook', 'Facebook')], default='email', max_length=20)),
                ('provider_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('two_fa_enabled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('banned', 'Banned'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'constraints': [models.UniqueConstraint(condition=models.Q(('phone_number__isnull', False)), fields=('phone_country_code', 'phone_number'), name='unique_phone'), models.CheckConstraint(condition=models.Q(('email__isnull', False), ('phone_number__isnull', False), _connector='OR'), name='users_must_have_contact')],
            },
        ),
    ]
